[package]
name = "sdkwork-api-log-assembly"
edition.workspace = true
license.workspace = true
version.workspace = true
description = "Generated API assembly for sdkwork-log application HTTP plane."

[lib]
name = "sdkwork_api_log_assembly"
path = "src/lib.rs"

[dependencies]
axum.workspace = true
tokio.workspace = true
sdkwork-web-bootstrap.workspace = true
sdkwork-web-core.workspace = true
http.workspace = true
sdkwork-database-sqlx = { workspace = true, default-features = false }
sdkwork-log-core.workspace = true
sdkwork-log-database-host.workspace = true
sdkwork-log-store-sqlx = { workspace = true, default-features = false, features = ["postgres"] }
sdkwork-log-tower-adapter.workspace = true
sdkwork-web-contract.workspace = true
sdkwork-routes-log-backend-api.workspace = true
