-- SDKWork log consolidated initialization baseline (postgres)
-- Generated by reset-database-initialization-state.mjs
-- Application is in initialization state: full DDL lives here; migrations/ is reserved for post-GA changes.

-- baseline source: ddl/baseline/postgres/0001_log_baseline.sql
-- SDKWork log foundation baseline (PostgreSQL).
-- Single table `log_request`: one row per recorded HTTP request (all API surfaces,
-- including webhook ingresses). traceId is server-owned and REQUIRED
-- (OBSERVABILITY_SPEC §2: access logs must use traceId). Fields follow the
-- OBSERVABILITY_SPEC §2 SHOULD list (service, environment, auth mode, stage,
-- status, duration); query_params and request_headers are captured redacted /
-- allow-listed only (DATABASE_SPEC §18: sensitive values MUST NOT be stored).
--
-- source: crates/sdkwork-log-store-sqlx/migrations/001_log_request.sql
CREATE TABLE IF NOT EXISTS log_request (
    id TEXT PRIMARY KEY NOT NULL,
    trace_id TEXT NOT NULL,
    request_id TEXT NOT NULL,
    tenant_id TEXT,
    user_id TEXT,
    user_name TEXT,
    api_surface TEXT NOT NULL,
    path TEXT NOT NULL,
    method TEXT NOT NULL,
    operation_id TEXT,
    service TEXT,
    environment TEXT,
    auth_mode TEXT,
    status_code INTEGER,
    duration_ms INTEGER,
    error_code INTEGER,
    failed_stage TEXT,
    query_params TEXT,
    request_headers TEXT,
    client_ip_hash TEXT,
    client_ip_masked TEXT,
    request_body TEXT,
    response_body TEXT,
    created_at BIGINT NOT NULL,
    expires_at BIGINT
);

CREATE INDEX IF NOT EXISTS idx_log_request_created
    ON log_request (created_at);

CREATE INDEX IF NOT EXISTS idx_log_request_trace
    ON log_request (trace_id);

CREATE INDEX IF NOT EXISTS idx_log_request_request
    ON log_request (request_id);

CREATE INDEX IF NOT EXISTS idx_log_request_tenant
    ON log_request (tenant_id);

CREATE INDEX IF NOT EXISTS idx_log_request_expires
    ON log_request (expires_at);

-- folded migration: migrations/postgres/0001_log_request_body.up.sql
-- sdkwork:migration
-- id: 0001_log_request_body
-- engine: postgres
-- module: log
-- purpose: Add redacted request/response body capture columns to log_request.
--   Only redacted body text is persisted (DATABASE_SPEC §18); the schema.yaml
--   contract version bumps to 1.1.0 with this change.
-- reversible: true
-- transactional: true
-- lock: table
-- contract_version: 1.1.0

BEGIN;

ALTER TABLE log_request ADD COLUMN IF NOT EXISTS request_body TEXT;
ALTER TABLE log_request ADD COLUMN IF NOT EXISTS response_body TEXT;

COMMIT;

-- folded migration: migrations/postgres/0002_log_request_user_ip.up.sql
-- sdkwork:migration
-- id: 0002_log_request_user_ip
-- engine: postgres
-- module: log
-- purpose: Add user_name and masked/hashed client_ip columns to log_request.
--   user_name snapshots the authenticated subject display name; client IP is
--   stored masked + SHA-256 hashed only (DATABASE_SPEC §18, raw IPs are never
--   persisted). The schema.yaml contract version bumps to 1.2.0.
-- reversible: true
-- transactional: true
-- lock: table
-- contract_version: 1.2.0

BEGIN;

ALTER TABLE log_request ADD COLUMN IF NOT EXISTS user_name TEXT;
ALTER TABLE log_request ADD COLUMN IF NOT EXISTS client_ip_hash TEXT;
ALTER TABLE log_request ADD COLUMN IF NOT EXISTS client_ip_masked TEXT;

COMMIT;
